[package]
name = "aws_code"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.5.10", features = ["behavior-version-latest"] }
aws-sdk-ec2 = "1.92.0"
tokio = { version = "1.41.1", features = ["full"] }
